# Generated by Django 3.1.5 on 2021-01-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow_users',
            field=models.ManyToManyField(to='follow_app.User'),
        ),
    ]
